_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: e5d42cfb-e841-4178-a745-1212856db095
name: Körte
mail: donci+marosgepkolcsonzodev@internode.hu
slogan: ''
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
